### ISSUE TITLE
Exclude issues from overview which is not there in diff view

### ISSUE THREAD

**Issue by sidd9433** [AmadeusITGroup/sonar-stash#159] opened 2017-10-31 13:15 UTC
Often I see there is a mismatch between the number of issues in the overview & the number of issues available in diff view of the PR, which is sometimes confusing for the developer.

Is there a way to have the overview, contains only those issues which are available in diff view?

**Comment by t-8ch** [comment] 2017-11-01 10:26
Duplicate of #58

**Closed by t-8ch** 2017-11-01 10:26 UTC
